version: '3'

networks:
  freepbx:
    driver: bridge
  databases:
    driver: bridge

services:
  db:
    image: mariadb:10.6.8
    container_name: izpbx-db
    ## 警告：如果升级镜像标签，需要进入容器执行 mysql_upgrade：
    ## source .env ; docker exec -it izpbx-db mysql_upgrade -u root -p$MYSQL_ROOT_PASSWORD
    command: --sql-mode=ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      - TZ
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      #- MARIADB_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_ROOT_PASSWORD}
      #- MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=${MYSQL_ALLOW_EMPTY_ROOT_PASSWORD}
    volumes:
      #- /etc/localtime:/etc/localtime:ro
      - ./data/db:/var/lib/mysql
      ## 注意：要避免 NAT 管理请使用：'network_mode: host'
      #network_mode: host
      ## 警告：如果禁用了 'network_mode: host'，请注释掉以下行
    networks:
      - databases
    ## 警告：如果被注释，数据库将暴露在容器外部
    ports:
      - ${APP_PORT_MYSQL}:3306

  # https://hub.docker.com/r/izdock/izpbx-asterisk/tags?page=1&ordering=last_updated
  freepbx:
    image: wiseowls/freepbx-quectel
    container_name: freepbx
    hostname: ${APP_FQDN}
    restart: unless-stopped
    user: root
    env_file:
      - stack.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data
    ## fail2ban 需要特权模式来管理 iptables
    privileged: true
    ulimits:
      nofile:
        soft: 8192
        hard: 32768
    ## 注意：要避免 SIP-RTP NAT 问题请使用：'network_mode: host'
    #    network_mode: host
    networks:
      - freepbx
      - databases
    ports:
      #- ${APP_PORT_HTTP}:${APP_PORT_HTTP}
      #- ${APP_PORT_HTTPS}:${APP_PORT_HTTPS}
      - ${APP_PORT_IAX}:${APP_PORT_IAX}
      - ${APP_PORT_IAX}:${APP_PORT_IAX}/udp
      - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}
      - ${APP_PORT_PJSIP}:${APP_PORT_PJSIP}/udp
      - ${APP_PORT_SIP}:${APP_PORT_SIP}/udp
      - ${APP_PORT_SIP}:${APP_PORT_SIP}
      - ${APP_PORT_WEBRTC}:${APP_PORT_WEBRTC}
      - ${APP_PORT_UCP_HTTP}:${APP_PORT_UCP_HTTP}
      - ${APP_PORT_UCP_HTTPS}:${APP_PORT_UCP_HTTPS}
      - ${APP_PORT_AMI}:${APP_PORT_AMI}
      - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}
      - ${APP_PORT_RTP_START}-${APP_PORT_RTP_END}:${APP_PORT_RTP_START}-${APP_PORT_RTP_END}/udp
      #- ${APP_PORT_DHCP}:${APP_PORT_DHCP}/udp
      #- ${APP_PORT_TFTP}:${APP_PORT_TFTP}
      #- ${APP_PORT_TFTP}:${APP_PORT_TFTP}/udp
      #- ${APP_PORT_NTP}:${APP_PORT_NTP}/udp
      #- ${APP_PORT_FOP2}:${APP_PORT_FOP2}
      #- ${APP_PORT_ZABBIX}:${APP_PORT_ZABBIX}
    labels:
      - "traefik.http.routers.freepbx.rule=Host(`freepbx.local`)"
      - "traefik.http.services.freepbx.loadbalancer.server.port=80"
