local=/izpbx.local/
domain=izpbx.local

#interface=eth0

# 禁用 resolv.conf，使用以下 DNS 进行查询
#no-resolv
#server=1.1.1.1
#server=8.8.8.8

# 其他设置
expand-hosts
domain-needed
bogus-priv
dns-forward-max=1024

# 启用 DHCP 服务器和地址范围
#dhcp-range=10.1.1.10,10.1.1.250,72h

# 在默认搜索中添加外部域名
#dhcp-option=option:domain-name,izpbx.local

# 默认网关地址（如果非当前 DNS 服务器）
#dhcp-option=3,10.1.1.1

# 外部 DNS 服务器（如果非当前 DNS 服务器）
#dhcp-option=6,10.1.1.1

# 外部 NTP 服务器
#dhcp-option=option:ntp-server,172.16.0.10

# 设置 NTP 时间服务器地址为运行 dnsmasq 的同一台机器
#dhcp-option=42,0.0.0.0

# 设置 TFTP 服务器地址（0.0.0.0 = 本机）
#dhcp-option=66,"0.0.0.0"

# 启用 TFTP 服务器
#enable-tftp
#tftp-root=/opt/izpbx/data/izpbx/var/lib/tftpboot/
#tftp-secure

## SRV 记录
# NTP 服务器发现
#srv-host =_ntp._udp.izpbx.local,ntp01.izpbx.local,123
#srv-host =_ntp._udp.izpbx.local,ntp02.izpbx.local,123

# DHCP 静态保留
#dhcp-host=00:00:00:00:00:00,pbx01,10.1.1.1
