[general]

interval=15			; 尝试连接设备的间隔秒数
smsdb=/var/lib/asterisk/smsdb
csmsttl=600

;------------------------------ 抖动缓冲区配置 --------------------------
;jbenable = yes			; 在 Quectel 通道接收端启用抖动缓冲区。默认值："no"。
				; 仅当发送端可创建抖动且接收端无法接受抖动时才启用。
				; Quectel 通道无法接受抖动，因此如果发送端可创建抖动，
				; 接收端启用的抖动缓冲区将始终被使用。

;jbforce = no			; 强制在 Quectel 通道接收端使用抖动缓冲区。默认值："no"。

;jbmaxsize = 200		; 抖动缓冲区的最大长度（毫秒）。

;jbresyncthreshold = 1000	; 帧时间戳跳跃阈值，超过此值抖动缓冲区将重新同步。
				; 有助于改善来自异常设备和程序的语音质量，
				; 特别是存在大幅时间戳跳跃/损坏时。默认值：1000。

;jbimpl = fixed			; 抖动缓冲区实现方式，用于 Quectel 通道接收端。
				; 当前有两种实现可选 - "fixed"（大小始终等于 jbmaxsize）
				; 和 "adaptive"（可变大小，实际为 IAX2 的新抖动缓冲）。
				; 默认值：fixed。

;jbtargetextra = 40		; 此选项仅在设置 'jbimpl = adaptive' 时生效。
				; 此选项表示新抖动缓冲区将扩充的大小（毫秒）。
				; 默认值为 40，因此不做修改的话，新抖动缓冲区
				; 的大小将设为抖动值加 40 毫秒。
				; 如果您的网络通常抖动较低
				; 但偶尔会出现峰值。

;jblog = no			; 启用抖动缓冲区帧日志。默认值："no"。
;-----------------------------------------------------------------------------------

[defaults]
; 现在您可以在此设置任何非必需的设备参数作为模板
;   您可以在任何 [device] 节中覆盖这些默认值

;context=incoming-mobile		; 来电上下文
context=from-trunk
group=0				    ; 呼叫组
rxgain=0			    ; 增加来电音量；可为负数
txgain=0			    ; 增加去电音量；可为负数
autodeletesms=yes		; 自动删除接收到的短信
resetquectel=yes		; 初始化时使用 ATZ 命令重置 Quectel
u2diag=-1			    ; 设置设备的 ^U2DIAG 参数（0 = 禁用除调制解调器外的所有功能）；-1 不使用 ^U2DIAG 命令
usecallingpres=yes		; 是否使用来电显示
callingpres=allowed_passed_screen ; 设置来电显示方式，默认使用网络设置
disablesms=no			; 禁用接收短信时从设备读取
                        ;  chan_quectel 目前在 SMS 接收方面存在 bug。通话过程中收到短信时
                        ;  chan_quectel 可能会崩溃。启用此选项可禁用短信接收。
                        ;  默认值 = no

language=en			    ; 设置通道默认语言
mindtmfgap=45			; 上一个 DTMF 结束到下一个 DTMF 开始的最小间隔（毫秒）
mindtmfduration=80		; DTMF 音调最小持续时间（毫秒）
mindtmfinterval=200		; 相同数字的 DTMF 结束之间的最小间隔（毫秒）

callwaiting=auto		; 如果为 'yes' 则允许来电等待；默认使用网络设置
				        ; 如果为 'no' 则忽略等待中的呼叫
disable=no			    ; 已废弃，由 initstate 替代：如果为 'yes' 则不加载此设备，直接忽略本节

initstate=start	    	; 指定设备的初始状态，必须为 'stop'、'start'、'remote' 之一
				        ;   'remove' 等同于 'disable=yes'

;exten=			        ; 来电起始分机号，仅在用户号码不可用时使用！同时设置为 CALLERID(ndid)

dtmf=relax			    ; 控制来电 DTMF 检测，可选值：
                        ;   off	   - 关闭 DTMF 音调检测，语音数据原样传递给 Asterisk
                        ;              用于网关或不在 AVR/拨号方案中使用 DTMF 时选择此值
                        ;   inband - 进行 DTMF 音调检测
                        ;   relax  - 类似 inband 但带 relaxdtmf 选项
                        ;  默认值为 'relax'，出于兼容性原因

; Quectel 必要设置
[quectel0]
audio=/dev/ttyUSB1		         ; 音频 tty 端口，如无其他设备则为 Simcom 设为 ttyUSB4
data=/dev/ttyUSB2		         ; AT 命令 tty 端口；无默认值
;quec_uac=1                              ; 如使用 UAC 模式请取消注释
;alsadev=hw:CARD=Android,DEV=0           ; 如使用 UAC 请取消注释，按需设置设备名称或索引


