[DEFAULT]
# 白名单 IP
ignoreip = 127.0.0.0/8 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16
bantime  = 300
findtime  = 3600
maxretry = 10
banaction = iptables-allports

destemail = root@localhost
sender = fail2ban@localhost.localdomain

## 封禁并发送邮件报告
#action = %(action_mwl)s

## 封禁但不发送邮件报告
action = %(action_)s

# 日志覆盖
logtarget = /var/log/fail2ban/fail2ban.log
apache_error_log = /var/log/httpd/*error*log
apache_access_log = /var/log/httpd/*access*log

## 取消注释以启用所有 jail
#enabled = true

# 发现并封禁重复攻击者
[recidive]
enabled  = true
logpath  = /var/log/fail2ban/fail2ban.log
action   = %(action_mwl)s
protocol = all
bantime  = 1814400 ; 3 周（ipset 最多支持 2147483 秒）
findtime = 15552000 ; 6 个月
maxretry = 30

[asterisk]
enabled = true
logpath = /var/log/asterisk/full

[freepbx]
enabled = true
logpath = /var/log/asterisk/freepbx_security.log

[apache-auth]
enabled = true

[apache-badbots]
enabled = true

[apache-noscript]
enabled = true

[apache-overflows]
enabled = true

[apache-nohome]
enabled = true

[apache-botsearch]
enabled = true

[apache-fakegooglebot]
enabled = true

[apache-shellshock]
enabled = true
